spring:
  application:
    name: course
  data:
    mongodb:
      uri: mongodb://chanchhaya:chanchhaya%2510@localhost:27024/
      database: db_course
server:
  tomcat:
    relaxed-query-chars: >
      |,[,],{,}

stream:
  image: http://localhost:8080/image/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://chanchhaya:chanchhaya%2510@db-course:27017/