spring:
  data:
    mongodb:
      uri: mongodb://preuniversity:PreUniversity2025@mongodb-pre:27017/

# https://course-api.istad.co
file-server:
  base-uri: 'https://course-api.istad.co/file/'
  server-path: '/file-server/'